project:
  type: website
  output-dir: .

website:
  title: "Tom Auer"
  navbar:
    left:
      - file: index.qmd
        text: About
      - file: projects.qmd
        text: Projects
      - file: pres.qmd
        text: Presentations

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

